changelog:
  repository: spring-projects/spring-framework
  sections:
    - title: ":star: New Features"
      labels:
        - "type: enhancement"
    - title: ":beetle: Bug Fixes"
      labels:
        - "type: bug"
        - "type: regression"
    - title: ":notebook_with_decorative_cover: Documentation"
      labels:
        - "type: documentation"
    - title: ":hammer: Dependency Upgrades"
      sort: "title"
      labels:
        - "type: dependency-upgrade"
